# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c29a652fd037af8072820aafaddedf78"
name = "customer-review-app"
handle = "customer-review-app-5"
application_url = "https://buying-stolen-examination-cellular.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = ["https://buying-stolen-examination-cellular.trycloudflare.com/auth/callback", "https://buying-stolen-examination-cellular.trycloudflare.com/auth/shopify/callback", "https://buying-stolen-examination-cellular.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
